version: "3.1"

services:
  scheduler:
    image: pengivan/dask
    hostname: dask-scheduler
    volumes: 
      - /Users/ivanpeng/PycharmProjects/rt_covid/data/:/data
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: pengivan/dask
    volumes: 
      - /Users/ivanpeng/PycharmProjects/rt_covid/data/:/data
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]

  # base-notebook:
  #   build:
  #     context: github.com/jupyter/docker-stacks.git#master:base-notebook
  #     dockerfile: Dockerfile
  #     args:
  #       PYTHON_VERSION: "3.7"
  #   image: jupyter/base-notebook:lab

  # notebook:
  #   image: pengivan/dask
  #   hostname: notebook
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"