version: "3.1"

services:
  scheduler:
    image: pengivan/dask:674a26a
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: pengivan/dask:674a26a
    hostname: dask-worker
    command: ["dask-worker", "tcp://scheduler:8786"]

  # base-notebook:
  #   build:
  #     context: github.com/jupyter/docker-stacks.git#master:base-notebook
  #     dockerfile: Dockerfile
  #     args:
  #       PYTHON_VERSION: "3.7"
  #   image: jupyter/base-notebook:lab

  notebook:
    image: pengivan/dask:674a26a
    hostname: notebook
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786" # Use this param to templatize in the future
    command:
      - jupyter
      - notebook
      - --ip=0.0.0.0
      - --allow-root 
